config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :boards do
    resources :columns do
      resources :tickets
    end
  end
  root "boards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :columns
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :board
  has_many :tickets
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :column
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        @board.columns.build(name: "Good").save
        @board.columns.build(name: "Bad").save
        @board.columns.build(name: "To improve").save

        format.html { redirect_to board_url(@board), notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to board_url(@board), notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    ActiveRecord::Base.transaction do
      @board.columns.destroy_all
      @board.destroy
    end

    respond_to do |format|
      format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_board
    @board = Board.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def board_params
    params.require(:board).permit(:name)
  end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :set_column, only: %i[ show ]

  def show
  end

  private

  def set_column
    @column = Column.find(params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_column, only: %i[ new create ]

  def new
    @ticket = @column.tickets.new
  end

  def create
    @ticket = @column.tickets.create!(ticket_params)

    respond_to do |format|
      format.html { redirect_to @column.board }
    end
  end

  private

  def set_column
    @board = Board.find(params[:board_id])
    @column = Column.find(params[:column_id])
  end

  def ticket_params
    params.require(:ticket).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>">
  <h1 class="text-2xl font-bold "><%= board.name %></h1>
</div>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= turbo_frame_tag "board" do %>
  <%= render "form", board: @board %>
<% end %>

app/views/boards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Boards</h1>

<div id="boards">
  <% @boards.each do |board| %>
    <%= render board %>
    <p>
      <%= link_to "Show this board", board %>
    </p>
  <% end %>
</div>

<%= link_to "New board", new_board_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/show.html.erb
<div class="container mx-auto flex-col h-fill px-12 ">
  <%= turbo_frame_tag "board" do %>
    <div class="w-fill">
      <div class="flex flex-row items-center">
        <%= render @board %>

        <div class="ml-8"></div>
        <%= link_to "Edit this board", edit_board_path(@board) %>
        <div class="mx-2">|</div>
        <%= link_to "Back to boards", boards_path, "data-turbo-frame": "_top" %>
        <div class="mx-2">|</div>
        <%= button_to "Destroy this board", board_path(@board), method: :delete %>
      </div>
    </div>
  <% end %>

  <div id="columns" class="flex flex-grow columns-3 gap-12 mt-12">
    <% @board.columns.each do |column| %>
      <div class="w-1/3">
        <%= render column %>
      </div>
    <% end %>
  </div>
</div>

app/views/columns/_column.html.erb
<div id="<%= dom_id column %>">
  <div class="w-full p-4 bg-slate-300 color-white rounded-lg shadow">
    <h3 class="text-2xl font-medium mb-6 mx-auto text-center"><%= column.name %></h3>
    <div class="columns-1 lg:columns-2">
      <% column.tickets.each do |ticket| %>
        <div class="pb-4">
          <%= render ticket %>
        </div>
      <% end %>
    </div>
    <div class="mt-1"></div>
    <%= turbo_frame_tag "new_ticket", src: new_board_column_ticket_path(column.board_id, column), target: "_top" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <title>Retrospective</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container h-screen mx-auto overflow-hidden">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
  <a href="#" class="block w-full p-6 text-black bg-white border border-gray-200 rounded-lg shadow">
    <h5 class="text-m"><%= ticket.message %></h5>
  </a>
</div>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= turbo_frame_tag "new_ticket" do %>
  <%= form_with(model: [@board, @column, @ticket], url: board_column_tickets_path(@board, @column)) do |form| %>
    <div class="flex items-center field">
      <%= form.text_field :message, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-full p-2.5" %>
      <button type="submit" class="custom-submit-button">
        <p class="text-2xl px-2">+</p>
      </button>
    </div>
  <% end %>
<% end %>